import type { FreeReport, FullReport } from "@/lib/types";

function slugFromListingUrl(url: string, index: number): string {
  try {
    const host = new URL(url).hostname.replace(/[^a-z0-9]+/gi, "-").slice(0, 48);
    return `revolve-full-report-${host || "listing"}-${index + 1}.md`;
  } catch {
    return `revolve-full-report-listing-${index + 1}.md`;
  }
}

export function freeReportToMarkdown(listingUrl: string, report: FreeReport): string {
  const scoreTenths = (report.score / 10).toFixed(1);
  const lines: string[] = [
    `# Free Airbnb listing preview`,
    ``,
    `**Listing:** ${listingUrl}`,
    ``,
    `**Preview score:** ${scoreTenths}/10 (model ${report.score}/100)`,
    ``,
    `## Summary`,
    ``,
    report.teaser,
    ``,
    `## Quick wins`,
    ``,
    ...report.quickWins.map((w, i) => `${i + 1}. ${w}`),
    ``,
    `---`,
    ``,
    `This is a free preview. Upgrade for full title rewrites, description draft, and prioritized actions.`,
    ``,
    `Generated by Revolve Co-Hosts`,
  ];
  return lines.join("\n");
}

function freeReportFilename(listingUrl: string): string {
  try {
    const host = new URL(listingUrl).hostname.replace(/[^a-z0-9]+/gi, "-").slice(0, 48);
    return `revolve-free-preview-${host || "listing"}.md`;
  } catch {
    return `revolve-free-preview.md`;
  }
}

export function downloadFreeReportMarkdown(listingUrl: string, report: FreeReport) {
  const md = freeReportToMarkdown(listingUrl, report);
  downloadTextFile(freeReportFilename(listingUrl), md, "text/markdown;charset=utf-8");
}

export function fullReportToMarkdown(listingUrl: string, report: FullReport): string {
  const lines: string[] = [
    `# Airbnb listing optimization report`,
    ``,
    `**Listing:** ${listingUrl}`,
    ``,
    `**Overall score:** ${report.score}/100`,
    ``,
    `## Recommended title`,
    ``,
    report.optimizedTitleOptions[0] ?? "",
    ``,
    `## All title options`,
    ``,
    ...report.optimizedTitleOptions.map((t, i) => `${i + 1}. ${t}`),
    ``,
    `## Optimized description`,
    ``,
    report.optimizedDescription,
    ``,
    `## Priority actions`,
    ``,
    ...report.priorityActions.map(
      (a) =>
        `### ${a.impact}: ${a.action}\n\n${a.reason}\n`,
    ),
    `## Market positioning`,
    ``,
    report.positioning,
    ``,
    `---`,
    ``,
    `Generated by Revolve Co-Hosts`,
  ];
  return lines.join("\n");
}

export type ReportEntryLite = { listingUrl: string; fullReport: FullReport };

export function bundleReportsToMarkdown(entries: ReportEntryLite[]): string {
  if (entries.length === 1) {
    return fullReportToMarkdown(entries[0].listingUrl, entries[0].fullReport);
  }
  const parts = entries.map((e, i) => {
    const block = fullReportToMarkdown(e.listingUrl, e.fullReport);
    return `<!-- Listing ${i + 1} -->\n\n${block}`;
  });
  return parts.join("\n\n\n---\n\n\n");
}

export function downloadTextFile(filename: string, content: string, mime: string) {
  const blob = new Blob([content], { type: mime });
  const a = document.createElement("a");
  a.href = URL.createObjectURL(blob);
  a.download = filename;
  a.click();
  URL.revokeObjectURL(a.href);
}

export function downloadReportMarkdown(
  listingUrl: string,
  report: FullReport,
  index: number,
) {
  const md = fullReportToMarkdown(listingUrl, report);
  downloadTextFile(slugFromListingUrl(listingUrl, index), md, "text/markdown;charset=utf-8");
}

export function downloadAllReportsMarkdown(entries: ReportEntryLite[]) {
  const md = bundleReportsToMarkdown(entries);
  const name =
    entries.length === 1
      ? slugFromListingUrl(entries[0].listingUrl, 0)
      : `revolve-full-reports-bundle-${entries.length}-listings.md`;
  downloadTextFile(name, md, "text/markdown;charset=utf-8");
}
